version: 1.0.{build}


image:
- Visual Studio 2017
- Visual Studio 2015


test: off


build:
  parallel: true


platform:
- x64


environment:
  matrix:
  - CONDA: 36
    CPP: 17
    CONFIG: Release
  - CONDA: 35
    CPP: 17
    CONFIG: Release
  - CONDA: 27
    CPP: 17
    CONFIG: Release


install:

# Configure environment
- ps: |
    # CMake architecture
    if ($env:PLATFORM -eq "x64") {
      $env:CMAKE_ARCH = "x64"
    }

    # CMake generator
    if ($env:APPVEYOR_JOB_NAME -like "*Visual Studio 2017*") {
      $env:CMAKE_GENERATOR = "Visual Studio 15 2017"
      $env:CXXFLAGS = "-permissive-"
    } else {
      $env:CMAKE_GENERATOR = "Visual Studio 14 2015"
    }

    # Python environment
    if ($env:PYTHON) {
      if ($env:PLATFORM -eq "x64") {
        $env:PATH = "C:\Python$env:PYTHON-x64\;C:\Python$env:PYTHON-x64\Scripts\;$env:PATH"
        $env:CMAKE_PREFIX_PATH = "C:\Python$env:PYTHON-x64\;C:\Python$env:PYTHON-x64\Scripts"
        $env:PYTHON_EXE = "C:\Python$env:PYTHON-x64\python.exe"
      } else {
        $env:PATH = "C:\Python$env:PYTHON\;C:\Python$env:PYTHON\Scripts\;$env:PATH"
        $env:CMAKE_PREFIX_PATH = "C:\Python$env:PYTHON\;C:\Python$env:PYTHON\Scripts"
        $env:PYTHON_EXE = "C:\Python$env:PYTHON\python.exe"
      }
      python -m pip install --disable-pip-version-check --user --upgrade pip wheel
    } elseif ($env:CONDA) {
      if ($env:PLATFORM -eq "x64") {
        $env:PATH = "C:\Miniconda$env:CONDA-x64\;C:\Miniconda$env:CONDA-x64\Scripts\;$env:PATH"
        $env:CMAKE_PREFIX_PATH = "C:\Miniconda$env:CONDA-x64\;C:\Miniconda$env:CONDA-x64\Scripts"
        $env:PYTHONHOME = "C:\Miniconda$env:CONDA-x64"
        $env:PYTHON_EXE = "C:\Miniconda$env:CONDA-x64\python.exe"
      } else {
        $env:PATH = "C:\Miniconda$env:CONDA\;C:\Miniconda$env:CONDA\Scripts\;$env:PATH"
        $env:CMAKE_PREFIX_PATH = "C:\Miniconda$env:CONDA\;C:\Miniconda$env:CONDA\Scripts"
        $env:PYTHONHOME = "C:\Miniconda$env:CONDA"
        $env:PYTHON_EXE = "C:\Miniconda$env:CONDA\python.exe"
      }
      conda update -y -q -n base conda
      conda install -y -q pip
      python -m pip install -U pip
    }
    # pip installation
    python -m pip install -U setuptools


build_script:
- python setup.py install
- python -c "import pyctest; import pyctest.pyctest; import pyctest.pycmake"
