# pyctest Travis CI file

cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.pyenv"


# The apt packages here install our compiled code dependencies.
matrix:
  include:
    # ------------------------------------------------------------------------ #
    #
    #   Python 2.7
    #
    # ------------------------------------------------------------------------ #
    # GCC 4.9
    - os: linux
      dist: trusty
      sudo: false
      language: python
      python: '2.7'
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - g++-4.9
            - build-essential
            - cmake
            - gpg
      env:
        - MATRIX_EVAL="CC=$(which gcc-4.9) && CXX=$(which g++-4.9) && BUILD_TYPE=RelWithDebInfo && CONDA_UPLOAD=1"
    # GCC 4.9
    - os: linux
      dist: trusty
      sudo: false
      language: python
      python: '2.7'
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - g++-4.9
            - build-essential
            - cmake
            - gpg
      env:
        - MATRIX_EVAL="CC=$(which gcc-4.9) && CXX=$(which g++-4.9) && BUILD_TYPE=RelWithDebInfo && CONDA_UPLOAD=0"
    # macOS
    - os: osx
      osx_image: xcode9.4
      language: ruby
      env:
        - MATRIX_EVAL="TRAVIS_PYTHON_VERSION=2.7 && MACOSX=1 && BUILD_TYPE=RelWithDebInfo && CONDA_UPLOAD=1"
    # macOS
    - os: osx
      osx_image: xcode9.4
      language: ruby
      env:
        - MATRIX_EVAL="TRAVIS_PYTHON_VERSION=2.7 && MACOSX=1 && BUILD_TYPE=RelWithDebInfo && CONDA_UPLOAD=0"
    # ------------------------------------------------------------------------ #
    #
    #   Python 3.5
    #
    # ------------------------------------------------------------------------ #
    # GCC 4.9
    - os: linux
      dist: trusty
      sudo: false
      language: python
      python: '3.5'
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - g++-4.9
            - build-essential
            - cmake3
            - gpg
      env:
        - MATRIX_EVAL="CC=$(which gcc-4.9) && CXX=$(which g++-4.9) && BUILD_TYPE=RelWithDebInfo && CONDA_UPLOAD=1"
    # GCC 4.9
    - os: linux
      dist: trusty
      sudo: false
      language: python
      python: '3.5'
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - g++-4.9
            - build-essential
            - cmake
            - gpg
      env:
        - MATRIX_EVAL="CC=$(which gcc-4.9) && CXX=$(which g++-4.9) && BUILD_TYPE=RelWithDebInfo && CONDA_UPLOAD=0"
    # macOS
    - os: osx
      osx_image: xcode9.4
      language: ruby
      env:
        - MATRIX_EVAL="TRAVIS_PYTHON_VERSION=3.5 && MACOSX=1 && BUILD_TYPE=RelWithDebInfo && CONDA_UPLOAD=1"
    # macOS
    - os: osx
      osx_image: xcode9.4
      language: ruby
      env:
        - MATRIX_EVAL="TRAVIS_PYTHON_VERSION=3.5 && MACOSX=1 && BUILD_TYPE=RelWithDebInfo && CONDA_UPLOAD=0"
    # ------------------------------------------------------------------------ #
    #
    #   Python 3.6
    #
    # ------------------------------------------------------------------------ #
    # GCC 4.9
    - os: linux
      dist: trusty
      sudo: false
      language: python
      python: '3.6'
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - g++-4.9
            - build-essential
            - cmake
            - gpg
      env:
        - MATRIX_EVAL="CC=$(which gcc-4.9) && CXX=$(which g++-4.9) && BUILD_TYPE=RelWithDebInfo && CONDA_UPLOAD=1"
    # GCC 4.9
    - os: linux
      dist: trusty
      sudo: false
      language: python
      python: '3.6'
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - g++-4.9
            - build-essential
            - cmake
            - gpg
      env:
        - MATRIX_EVAL="CC=$(which gcc-4.9) && CXX=$(which g++-4.9) && BUILD_TYPE=RelWithDebInfo && CONDA_UPLOAD=0"
    # macOS
    - os: osx
      osx_image: xcode9.4
      language: ruby
      env:
        - MATRIX_EVAL="TRAVIS_PYTHON_VERSION=3.6 && MACOSX=1 && BUILD_TYPE=RelWithDebInfo && CONDA_UPLOAD=1"
    # macOS
    - os: osx
      osx_image: xcode9.4
      language: ruby
      env:
        - MATRIX_EVAL="TRAVIS_PYTHON_VERSION=3.6 && MACOSX=1 && BUILD_TYPE=RelWithDebInfo && CONDA_UPLOAD=0"
    # ------------------------------------------------------------------------ #


before_install:
    - eval "${MATRIX_EVAL}"
    - if [[ -n "${MACOSX}" ]]; then
        CC=$(which clang) ;
        CXX=$(which clang++) ;
      fi
    - if [[ "${CONDA_UPLOAD}" -eq 0 ]]; then
        TWINE_UPLOAD=0 ;
      fi
    - if [[ "${TRAVIS_BRANCH}" != "master" ]] || [[ "${TRAVIS_PULL_REQUEST}" != "false" ]]; then
        CONDA_UPLOAD=0 ;
        TWINE_UPLOAD=0 ;
      fi
    - export CONDA_UPLOAD
    - export TWINE_UPLOAD
    - export CC=${CC}
    - export CXX=${CXX}
    - export PYCTEST_BUILD_TYPE=${BUILD_TYPE}
    - echo "CC = ${CC} $(${CC} -dumpversion)"
    - echo "CXX = ${CXX} $(${CXX} -dumpversion)"
    - mkdir -p .gpg
    - openssl aes-256-cbc -K $encrypted_66d16737a1a4_key -iv $encrypted_66d16737a1a4_iv -in all.gpg.enc -out .gpg/all.gpg -d
    - gpg --import .gpg/all.gpg

install:
    - export CPY_MAJOR=$(echo "${TRAVIS_PYTHON_VERSION}" | sed 's/\./ /g' | awk '{print $1}')
    - export CPY_OS=Linux
    - if [[ -n "${MACOSX}" ]]; then export CPY_OS=MacOSX ; fi
    - if [[ "${CONDA_UPLOAD}" -gt 0 ]]; then wget https://repo.continuum.io/miniconda/Miniconda${CPY_MAJOR}-latest-${CPY_OS}-x86_64.sh -O miniconda.sh ; fi
    - if [[ "${CONDA_UPLOAD}" -gt 0 ]]; then bash miniconda.sh -b -p $HOME/miniconda ; fi
    - if [[ "${CONDA_UPLOAD}" -gt 0 ]]; then export PATH="$HOME/miniconda/bin:$PATH" ; fi
    - if [[ "${CONDA_UPLOAD}" -gt 0 ]]; then hash -r ; fi
    - if [[ "${CONDA_UPLOAD}" -gt 0 ]]; then conda config --set always_yes yes --set changeps1 no ; fi
    - if [[ "${CONDA_UPLOAD}" -gt 0 ]]; then conda update -q conda ; fi
    - if [[ "${CONDA_UPLOAD}" -gt 0 ]]; then conda info -a ; fi
    - if [[ "${CONDA_UPLOAD}" -gt 0 ]]; then conda create -q -n test-env python=${TRAVIS_PYTHON_VERSION} anaconda anaconda-client conda-build ; fi
    - if [[ "${TWINE_UPLOAD}" -gt 0 ]]; then python${TRAVIS_PYTHON_VERSION} -m pip install twine ; fi
    - if [[ "${TWINE_UPLOAD}" -gt 0 ]]; then echo -e "[distutils]\nindex-servers = \n    pypi\n\n[pypi]\nusername:jrmadsen\npassword:${TWINE_TOKEN}\n" > ${HOME}/.pypirc ; fi

script:
    #
    # Python testing
    #
    - if [[ "${CONDA_UPLOAD}" -gt 0 ]]; then
          source activate test-env ;
          conda config --set anaconda_upload yes ;
          python update-conda-yaml.py ;
          conda-build --user jrmadsen --token ${ANACONDA_TOKEN} . ;
      elif [[ "${TWINE_UPLOAD}" -gt 0 ]]; then
          python${TRAVIS_PYTHON_VERSION} setup.py bdist ;
          cd dist ;
          gpg --detach-sign -a *.tar.gz ;
          eval $(python${TRAVIS_PYTHON_VERSION} -m twine upload *.tar.gz *.tar.gz.asc) ;
      else
          python${TRAVIS_PYTHON_VERSION} setup.py install ;
          mkdir -p ${HOME}/pyctest-test ;
          cd ${HOME}/pyctest-test ;
          python${TRAVIS_PYTHON_VERSION} -c "import pyctest; import pyctest.pyctest; import pyctest.pycmake" ;
      fi
