package:
  name: pyctest
  version: '0.0.1'

build:
  number: 0

source:
  git_rev: 5efca17f4aef7adeb23d8b01e9c2bf4b0381a0d3
  git_url: https://github.com/jrmadsen/pyctest.git

requirements:
  host:
  - python
  - setuptools
  - cmake

test:
  imports:
  - pyctest
  - pyctest.pyctest
  - pyctest.pycmake

about:
  home: https://jrmadsen.github.io/pyctest/
  license: MIT
  summary: "Python bindings to select portions of CMake/CTest package -- enabling generation of CTests for CDash submission without a CMake build system"
