package:
  name: pyctest
  version: '0.0.1'

build:
  ignore_prefix_files: True
  #binary_relocation: False
  detect_binary_files_with_prefix: False

source:
  git_rev: 4003891d4d493d8695bdd3854f510d0eaec4e01a
  git_url: https://github.com/jrmadsen/pyctest.git

requirements:
  build:
  - cmake
  - setuptools
  - openssl
  host:
  - python
  - openssl
  run:
  - openssl

test:
  imports:
  - pyctest.pyctest
  - pyctest.pycmake

about:
  home: https://jrmadsen.github.io/pyctest/
  license: MIT
  summary: "Python bindings to select portions of CMake/CTest package -- enabling generation of CTests for CDash submission without a CMake build system"
