package:
  name: pyctest
  version: '0.0.10'

build:
  number: 0
  binary_relocation: False
  script: "{{ PYTHON }} setup.py install"  # [not win]
  script_env:
    - TMPDIR
    - CC
    - CXX

source:
  git_rev: 4cabc210e55f64fab08e88376718ecc40c14daf4
  git_url: https://github.com/jrmadsen/pyctest.git

requirements:
  build:
    - {{ compiler('c') }}  # [win]
    - {{ compiler('cxx') }}  # [win]
    - python={{ python }}  # [win]
    - cmake
    - git
  host:
    - python
    - pip
    - setuptools
    - openssl
    - curl
  run:
    - python
    - openssl
    - curl
    - libuv  # [not win]

test:
  imports:
    - pyctest
    - pyctest.pyctest
    - pyctest.pycmake
    - pyctest.helpers
    - pyctest.cmake
    - pyctest.ctest
    - pyctest.cpack

about:
  home: https://jrmadsen.github.io/pyctest/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Python bindings to select portions of CMake/CTest package -- enabling generation of CTests for CDash submission without a CMake build system'
  doc_url: https://pyctest.readthedocs.io/en/latest/
  dev_url: http://github.com/jrmadsen/pyctest
