package:
  name: pyctest
  version: '0.0.9'

build:
  number: 0
  binary_relocation: False
  script_env:
  - TMPDIR
  - CC
  - CXX
  - CPATH
  - LD_LIBRARY_PATH
  - DYLD_LIBRARY_PATH
  - PYCTEST_BUILD_TYPE
  - CMAKE_PREFIX_PATH
  - PYCTEST_CMAKE_PREFIX_PATH
  - PYCTEST_CMAKE_INCLUDE_PATH
  - PYCTEST_CMAKE_LIBRARY_PATH
  script:
    - "{{ PYTHON }} setup.py install"

source:
  git_rev: da2e6ab435467d8e51cc6488750f87a96ab7c227
  git_url: https://github.com/jrmadsen/pyctest.git

requirements:
  host:
  - python
  - setuptools
  - cmake
  - openssl
  - {{ compiler('c') }} # [not win]
  - {{ compiler('cxx') }} # [not win]
  run:
  - python
  - openssl

test:
  imports:
  - pyctest
  - pyctest.pyctest
  - pyctest.pycmake
  - pyctest.helpers
  commands:
  - cd examples/Basic && ./basic.py

about:
  home: https://jrmadsen.github.io/pyctest/
  license: MIT
  summary: "Python bindings to select portions of CMake/CTest package -- enabling generation of CTests for CDash submission without a CMake build system"
